### ISSUE TITLE
Text boxes dont always show the text when writing

### ISSUE THREAD

**Issue by Cnordg** [sopra-fs23-group-13/meme-it-client#167] opened 2023-05-23 13:20 UTC
<img width="586" alt="Screenshot 2023-05-23 at 15 12 38" src="https://github.com/sopra-fs23-group-13/meme-it-client/assets/91025733/04a885af-0856-4cc8-8771-96411ebd5d42">

Note: im using safari in private tab (might not be a problem on chrome or Firefox)

**Comment by danielLutziger** [comment] 2023-05-24 07:47
this is a safari issue. Will take a look into it. FF, Chrome and Edge work properly

**Comment by danielLutziger** [comment] 2023-05-24 08:30
was able to reproduce issue in safari. should be fixed so that it still works for ff and chrome. it was due to elements which are not available in safari and used for different values. i replaced them with more generalized attributes.

**Comment by danielLutziger** [comment] 2023-05-24 08:36
@henrik pls test branch [bug-168 ](https://github.com/sopra-fs23-group-13/meme-it-client/pull/172) (branch: bug-168)

**Comment by henrik** [comment] 2023-05-24 08:57
Wrong Henrik.

**Comment by danielLutziger** [comment] 2023-05-24 09:32
@Cnordg pls test branch https://github.com/sopra-fs23-group-13/meme-it-client/pull/172(branch: bug-168)

**Comment by danielLutziger** [comment] 2023-05-24 14:15
https://github.com/sopra-fs23-group-13/meme-it-client/pull/176

**Closed** 2023-05-25 08:00 UTC
Labels: bug
